Review request
Zamtakaish/JavaMastery pull request #1
Opened 2021-05-23 17:03 UTC by Zamtakaish

2021-05-23 17:04 UTC, roman-karpovich reviewed
hey

2021-05-24 11:03 UTC, pgutnik requested changes
Looks good, but some changes are required.

2021-05-24 11:03 UTC, pgutnik commented on README.md
> +# Simple RESTfull app
ping

2021-05-24 11:03 UTC, pgutnik commented on src/main/java/com/mastery/java/task/dto/Employee.java
> +}
Add equals/hashcode overrides.
https://www.baeldung.com/java-equals-hashcode-contracts

2021-05-24 11:03 UTC, pgutnik commented on src/main/java/com/mastery/java/task/dao/EmployeeDao.java
> +    private void isEmployeeExist(int id) {
Seems a bit redundant. Maybe deleteById(int) will throw it's own exception that you can rethrow up?

2021-05-24 11:03 UTC, pgutnik commented on src/main/java/com/mastery/java/task/dao/EmployeeDao.java
> +        Optional<Employee> employee = repository.findById(id);
Can be replaced by isEmployeeExists.

2021-05-24 11:03 UTC, pgutnik commented on src/main/java/com/mastery/java/task/dto/Employee.java
> +
Maybe add a constructor with all fields?

2021-05-24 11:03 UTC, pgutnik commented on src/test/java/com/mastery/java/task/controller/EmployeeControllerTest.java
> +    public void shouldListAllUsers_whenGetMethodCalled() throws Exception {
No need to use "_" just write long names, welcome to Java naming.

2021-05-24 11:03 UTC, pgutnik commented on src/test/java/com/mastery/java/task/controller/EmployeeControllerTest.java
> +    public void setTestEmployee(){
createTestEmployee is better

2021-05-24 11:03 UTC, pgutnik commented on src/test/java/com/mastery/java/task/controller/EmployeeControllerTest.java
> +        mvc.perform(get("/employees/" + id)
Add a new line to separate When from Then parts of the test.

2021-05-24 11:03 UTC, pgutnik commented on src/test/java/com/mastery/java/task/controller/EmployeeControllerTest.java
> +        ObjectMapper mapper = new ObjectMapper();
Can this mapper be extracted to a test class field?

2021-05-24 11:03 UTC, pgutnik commented on src/test/java/com/mastery/java/task/dao/EmployeeDaoTest.java
> +    private void setTestEmployee(){
Rename to createTestEmployee()

2021-05-24 11:03 UTC, pgutnik commented on src/test/java/com/mastery/java/task/dao/EmployeeDaoTest.java
> +        employeeList.add(testEmployee);
Replace with Arrays.asList()

2021-05-24 12:29 UTC, merged